# Generated by Django 6.0.3 on 2026-04-08 12:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('typeObjet', models.CharField(max_length=30)),
                ('surfaceMin', models.FloatField()),
                ('surfaceMax', models.FloatField()),
                ('estPremium', models.BooleanField(default=False)),
                ('difficulte', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('consentementRGPD', models.BooleanField(default=False)),
                ('soldePieces', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AchatPatron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAchat', models.DateField(auto_now_add=True)),
                ('typePayement', models.CharField(max_length=30)),
                ('nombrePieceUtilisees', models.IntegerField(default=0)),
                ('montantEuro', models.FloatField(default=0.0)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patron')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surfaceCalculee', models.FloatField()),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(default='En cours', max_length=30)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordreProposition', models.IntegerField()),
                ('estSelectionnerParUtilisateur', models.BooleanField(default=False)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patron')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='core.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Tutoriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('typeTutoriel', models.CharField(max_length=30)),
                ('urlVideoOuArticle', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=30)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoriels', to='core.patron')),
            ],
        ),
        migrations.CreateModel(
            name='Vetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomVetement', models.CharField(max_length=30)),
                ('photoURL', models.ImageField(upload_to='vetements/')),
                ('typeVetement', models.CharField(max_length=30)),
                ('largeur', models.FloatField()),
                ('hauteur', models.FloatField()),
                ('surfaceTotale', models.FloatField()),
                ('surfaceTaches', models.FloatField(default=0.0)),
                ('surfaceTrous', models.FloatField(default=0.0)),
                ('surfaceExploitable', models.FloatField()),
                ('etat', models.CharField(max_length=30)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='vetements',
            field=models.ManyToManyField(to='core.vetement'),
        ),
    ]
