# Generated by Django 6.0.3 on 2026-04-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='envies_creation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='niveau_couture',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
