# Generated by Django 6.0.3 on 2026-05-27 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patron_materiel_tutoriel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapePatron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('conseil', models.TextField(blank=True, null=True)),
                ('materiaux_etape', models.TextField(blank=True, null=True)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='core.patron')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
