# Generated by Django 6.0.3 on 2026-05-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_etapepatron'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetement',
            name='qualite',
            field=models.IntegerField(default=3),
        ),
    ]
