# Generated by Django 6.0.3 on 2026-05-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vetement_qualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetement',
            name='couleur',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
