# Generated by Django 6.0.3 on 2026-05-29 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vetement_couleur'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_like', models.DateTimeField(auto_now_add=True)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.patron')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patron_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'patron')},
            },
        ),
        migrations.CreateModel(
            name='ProgressionProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape_actuelle', models.IntegerField(default=1)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
                ('termine', models.BooleanField(default=False)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='core.patron')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'patron')},
            },
        ),
    ]
