# Generated by Django 6.0.3 on 2026-05-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_progressionprojet_patronlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='matiere_requise',
            field=models.TextField(blank=True, help_text='Matières acceptées, séparées par des virgules (ex: coton,lin,viscose). Laisser vide = toute matière acceptée.', null=True),
        ),
        migrations.AddField(
            model_name='progressionprojet',
            name='vetements_projet',
            field=models.ManyToManyField(blank=True, related_name='progressions_projet', to='core.vetement'),
        ),
        migrations.AddField(
            model_name='vetement',
            name='matiere',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
