# Generated by Django 6.0.3 on 2026-06-14 21:59

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_assign_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapepatron',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patrons/etapes/'),
        ),
        migrations.AddField(
            model_name='patron',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrons_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patron',
            name='pdf_patron',
            field=models.FileField(blank=True, help_text='PDF des planches de patron à imprimer / découper.', null=True, storage=core.models.raw_media_storage, upload_to='patrons/pdf/'),
        ),
        migrations.CreateModel(
            name='PiecePatron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('largeur_cm', models.FloatField(blank=True, null=True)),
                ('hauteur_cm', models.FloatField(blank=True, null=True)),
                ('svg', models.FileField(blank=True, help_text='Fichier SVG de la forme à découper.', null=True, storage=core.models.raw_media_storage, upload_to='patrons/pieces/')),
                ('ordre', models.IntegerField(default=0)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='core.patron')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
