# Generated by Django 6.0.3 on 2026-06-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_etapepatron_image_patron_createur_patron_pdf_patron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetement',
            name='defauts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vetement',
            name='detourage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vetement',
            name='echelle_cm_px',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
