# Generated by Django 5.2.3 on 2026-06-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_vetement_defauts_vetement_detourage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='dateConsentementRGPD',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
