# Generated by Django 5.2.3 on 2026-06-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_utilisateur_dateconsentementrgpd'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email_verifie',
            field=models.BooleanField(default=False),
        ),
    ]
