# Generated by Django 5.2.3 on 2026-08-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_utilisateur_email_verifie'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetement',
            name='numeroIdentite',
            field=models.CharField(blank=True, help_text="Numéro d'identité facultatif, saisi si le tissu a déjà été suivi ailleurs sur l'app.", max_length=50, null=True),
        ),
    ]
