# Generated by Django 5.2.3 on 2026-08-13 12:54

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_vetement_numeroidentite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapepatron',
            name='video_url',
        ),
        migrations.AddField(
            model_name='progressionprojet',
            name='geste_actuelle',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='GestePatron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, help_text="Vidéo du geste, jouée en fond d'écran pendant l'étape.", null=True, storage=core.models.video_media_storage, upload_to='patrons/gestes/videos/')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestes', to='core.etapepatron')),
                ('pieces', models.ManyToManyField(blank=True, related_name='gestes', to='core.piecepatron')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
