# Generated by Django 5.2.3 on 2026-08-13 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_etapepatron_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDeCoupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_coupe', to='core.patron')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_coupe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'patron')},
            },
        ),
    ]
