# Generated by Django 5.2.3 on 2026-08-15 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_plandecoupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefiVille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(default='Lyon', max_length=60)),
                ('titre', models.CharField(max_length=160)),
                ('objectif_m2', models.FloatField(default=500)),
                ('date_fin', models.DateField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ecusson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('nom', models.CharField(max_length=60)),
                ('categorie', models.CharField(choices=[('matieres', 'Matières'), ('defis', 'Défis & rythme'), ('entraide', 'Entraide & savoir')], default='matieres', max_length=20)),
                ('rang', models.CharField(choices=[('toile', 'Toile'), ('laine', 'Laine'), ('or', 'Or')], default='toile', max_length=10)),
                ('condition', models.CharField(blank=True, help_text='Libellé court : « 148 pièces », « 30 jours »…', max_length=60)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icone', models.CharField(default='etoile', max_length=30)),
                ('couleur_haut', models.CharField(default='#6BE0A0', max_length=9)),
                ('couleur_bas', models.CharField(default='#12633A', max_length=9)),
                ('niveau_requis', models.PositiveIntegerField(default=0)),
                ('prix_pieces', models.PositiveIntegerField(default=0, help_text='0 = non vendu en boutique.')),
                ('rarete', models.PositiveIntegerField(default=0, help_text="% de couturières qui l'ont obtenu.")),
                ('secret', models.BooleanField(default=False, help_text="Affiché « ? » tant qu'il n'est pas obtenu.")),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['categorie', 'ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('libelle', models.CharField(max_length=140)),
                ('detail', models.CharField(blank=True, max_length=160)),
                ('periode', models.CharField(choices=[('jour', 'Quotidienne'), ('semaine', 'Hebdomadaire')], default='jour', max_length=10)),
                ('objectif', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=20)),
                ('pieces', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['periode', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nom', models.CharField(default='Toile', max_length=40)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='AnnonceTroc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=160)),
                ('sens', models.CharField(choices=[('donne', 'À donner'), ('cherche', 'Recherche')], default='donne', max_length=10)),
                ('surface_m2', models.FloatField(default=0.0)),
                ('distance_m', models.PositiveIntegerField(default=800)),
                ('motif', models.CharField(default='lin', max_length=20)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('reservee', 'Réservée'), ('close', 'Close')], default='ouverte', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces_troc', to=settings.AUTH_USER_MODEL)),
                ('preneuse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocs_pris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteEntraide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialites', models.CharField(blank=True, default='Denim, fermetures', max_length=120)),
                ('en_ligne', models.BooleanField(default=True)),
                ('delai_reponse_min', models.PositiveIntegerField(default=5)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispo_entraide', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.PositiveIntegerField(default=0)),
                ('score_b', models.PositiveIntegerField(default=0)),
                ('mise_pieces', models.PositiveIntegerField(default=20)),
                ('xp_gain', models.PositiveIntegerField(default=60)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('propose', 'Proposé'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=12)),
                ('joueuse_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_a', to=settings.AUTH_USER_MODEL)),
                ('joueuse_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='EvenementCommunaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('accroche', models.CharField(blank=True, help_text="Ligne courte affichée sur la carte de l'agenda.", max_length=160)),
                ('format_evenement', models.CharField(choices=[('presentiel', 'Sur place'), ('en_ligne', 'En ligne'), ('marathon', 'Marathon')], default='presentiel', max_length=12)),
                ('date_evenement', models.DateField()),
                ('heure_debut', models.CharField(blank=True, default='14h', max_length=10)),
                ('heure_fin', models.CharField(blank=True, default='18h', max_length=10)),
                ('lieu', models.CharField(blank=True, max_length=120)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('machines_dispo', models.PositiveIntegerField(default=0)),
                ('xp_gain', models.PositiveIntegerField(default=30)),
                ('duree', models.CharField(blank=True, max_length=40)),
                ('motif', models.CharField(default='denim', max_length=20)),
                ('animatrice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_animes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_evenement'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rappel_actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evenementcommunaute')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'evenement')},
            },
        ),
        migrations.AddField(
            model_name='evenementcommunaute',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='evenements', through='core.InscriptionEvenement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OffreBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('categorie', models.CharField(choices=[('pack', 'Offre du jour'), ('patron', 'Patrons'), ('gel', 'Bonus de série'), ('ecusson', 'Écussons')], default='patron', max_length=12)),
                ('prix_pieces', models.PositiveIntegerField(default=50)),
                ('prix_barre', models.PositiveIntegerField(default=0, help_text="Prix d'origine affiché barré. 0 = aucun.")),
                ('remise', models.CharField(blank=True, help_text='Ex. « -10% »', max_length=10)),
                ('quantite_gels', models.PositiveIntegerField(default=0)),
                ('niveau_requis', models.PositiveIntegerField(default=0)),
                ('motif', models.CharField(default='denim', max_length=20)),
                ('mise_en_avant', models.BooleanField(default=False, help_text='Affiché en « offre du jour ».')),
                ('fin_offre', models.DateTimeField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('ecusson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ecusson')),
                ('patron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patron')),
            ],
            options={
                'ordering': ['categorie', 'ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PalierSaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('xp_requis', models.PositiveIntegerField()),
                ('titre', models.CharField(default='Coffre', max_length=120)),
                ('detail', models.CharField(blank=True, max_length=160)),
                ('pieces', models.PositiveIntegerField(default=0)),
                ('gels', models.PositiveIntegerField(default=0)),
                ('ecusson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ecusson')),
                ('patron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patron')),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers', to='core.saison')),
            ],
            options={
                'ordering': ['saison', 'numero'],
                'unique_together': {('saison', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='PieceDuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120)),
                ('surface_m2', models.FloatField(default=0.0)),
                ('motif', models.CharField(default='denim', help_text='denim / lin / toile — couleur de la vignette.', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_comptees', to='core.duel')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_duel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ProfilJeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('serie_actuelle', models.PositiveIntegerField(default=0)),
                ('serie_record', models.PositiveIntegerField(default=0)),
                ('derniere_activite', models.DateField(blank=True, null=True)),
                ('gels', models.PositiveIntegerField(default=2)),
                ('ville', models.CharField(blank=True, default='Lyon', max_length=60)),
                ('quartier', models.CharField(blank=True, default='Croix-Rousse', max_length=60)),
                ('arrondissement', models.CharField(blank=True, default='Lyon 4ᵉ', max_length=20)),
                ('code_atelier', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('jours_semaine', models.CharField(blank=True, default='', max_length=20)),
                ('semaine_cle', models.CharField(blank=True, default='', max_length=16)),
                ('parraine_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleules', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_jeu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionEntraide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Séparés par des virgules : denim,machine', max_length=120)),
                ('motif', models.CharField(blank=True, help_text='Vignette photo : denim / lin / toile / laine', max_length=20)),
                ('resolue', models.BooleanField(default=False)),
                ('xp_gain', models.PositiveIntegerField(default=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_entraide', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseEntraide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('validee', models.BooleanField(default=False, help_text="Réponse retenue par l'autrice de la question.")),
                ('coeurs', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_entraide', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='core.questionentraide')),
            ],
            options={
                'ordering': ['-validee', 'date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('type_salon', models.CharField(choices=[('quartier', 'Quartier'), ('sos', 'SOS en direct'), ('theme', 'Thématique')], default='quartier', max_length=12)),
                ('motif', models.CharField(default='denim', max_length=20)),
                ('defi_titre', models.CharField(blank=True, default='Défi coop du salon', max_length=120)),
                ('defi_objectif_m2', models.FloatField(default=0.0)),
                ('defi_avance_m2', models.FloatField(default=0.0)),
                ('defi_echeance', models.DateField(blank=True, null=True)),
                ('membres', models.ManyToManyField(blank=True, related_name='salons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True)),
                ('type_message', models.CharField(choices=[('texte', 'Texte'), ('photos', 'Photos'), ('troc', 'Annonce de troc')], default='texte', max_length=10)),
                ('motifs', models.CharField(blank=True, help_text='Vignettes de la galerie, séparées par des virgules : denim,toile', max_length=60)),
                ('coeurs', models.PositiveIntegerField(default=0)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.annoncetroc')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_salon', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.salon')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='TransactionPieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=140)),
                ('montant', models.IntegerField(help_text='Négatif pour un achat, positif pour un gain.')),
                ('icone', models.CharField(default='piece', max_length=20)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_pieces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.CreateModel(
            name='Amitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptee', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amities_envoyees', to=settings.AUTH_USER_MODEL)),
                ('vers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amities_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('de', 'vers')},
            },
        ),
        migrations.CreateModel(
            name='CoffreQuotidien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_cle', models.CharField(max_length=16)),
                ('pieces', models.PositiveIntegerField(default=30)),
                ('ouvert', models.BooleanField(default=False)),
                ('date_ouverture', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffres_quotidiens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'periode_cle')},
            },
        ),
        migrations.CreateModel(
            name='ContributionDefiVille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(default='Croix-Rousse', max_length=60)),
                ('m2', models.FloatField(default=0.0)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions_defi', to=settings.AUTH_USER_MODEL)),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.defiville')),
            ],
            options={
                'unique_together': {('defi', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='EcussonObtenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('ecusson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obtentions', to='core.ecusson')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecussons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_obtention'],
                'unique_together': {('utilisateur', 'ecusson')},
            },
        ),
        migrations.CreateModel(
            name='PalierReclame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reclamation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers_reclames', to=settings.AUTH_USER_MODEL)),
                ('palier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='core.paliersaison')),
            ],
            options={
                'unique_together': {('utilisateur', 'palier')},
            },
        ),
        migrations.CreateModel(
            name='QueteUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_cle', models.CharField(max_length=16)),
                ('avancement', models.PositiveIntegerField(default=0)),
                ('terminee', models.BooleanField(default=False)),
                ('recompense_versee', models.BooleanField(default=False)),
                ('quete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avancements', to='core.quete')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quetes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'quete', 'periode_cle')},
            },
        ),
        migrations.CreateModel(
            name='ParticipationLigue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligue', models.CharField(choices=[('bois', 'Ligue Bois'), ('toile', 'Ligue Toile'), ('argent', 'Ligue Argent'), ('or', 'Ligue Or'), ('platine', 'Ligue Platine'), ('diamant', 'Ligue Diamant')], default='or', max_length=20)),
                ('xp_saison', models.PositiveIntegerField(default=0)),
                ('pieces_finies', models.PositiveIntegerField(default=0)),
                ('m2_sauves', models.FloatField(default=0.0)),
                ('bilan_vu', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_ligue', to=settings.AUTH_USER_MODEL)),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.saison')),
            ],
            options={
                'ordering': ['-xp_saison'],
                'unique_together': {('utilisateur', 'saison')},
            },
        ),
    ]
