# Generated by Django 5.2.3 on 2026-08-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_defiville_ecusson_quete_saison_annoncetroc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiljeu',
            name='teinte',
            field=models.CharField(blank=True, choices=[('t-or', 'Or'), ('t-vert', 'Vert'), ('t-violet', 'Violet'), ('t-corail', 'Corail')], default='', max_length=12),
        ),
    ]
