# Generated by Django 5.2.3 on 2026-08-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_profiljeu_teinte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annoncetroc',
            options={'ordering': ['-sens', '-date_creation']},
        ),
        migrations.AddField(
            model_name='quete',
            name='cta_libelle',
            field=models.CharField(default='Continuer', max_length=60),
        ),
        migrations.AddField(
            model_name='quete',
            name='cta_route',
            field=models.CharField(default='patrons', help_text="Nom d'URL Django vers l'écran qui permet d'accomplir la quête.", max_length=60),
        ),
    ]
