# Generated by Django 5.2.3 on 2026-08-16 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_paliersaison_points_requis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amitie',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='amitie',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiljeu',
            name='niveau_vu',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amitie',
            name='acceptee',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('amitie_demande', "Demande d'amitié"), ('amitie_acceptee', 'Amitié acceptée'), ('duel', 'Duel'), ('coffre', 'Coffre disponible'), ('niveau', 'Montée de niveau'), ('reponse', 'Réponse à ta question'), ('salon', 'Message de salon'), ('evenement', 'Événement'), ('troc', 'Troc de chutes'), ('saison', 'Saison'), ('defi', 'Défi de ville')], max_length=20)),
                ('titre', models.CharField(max_length=160)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('lien', models.CharField(blank=True, help_text='URL déjà résolue.', max_length=200)),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('emetteur', models.ForeignKey(blank=True, help_text="Couturière à l'origine de l'événement, si elle existe.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_emises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', 'lue', '-date_creation'], name='core_notifi_destina_5df215_idx')],
            },
        ),
    ]
