# Generated by Django 5.2.3 on 2026-08-16 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_notifications_et_amities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributiondefiville',
            options={'ordering': ['-m2']},
        ),
        migrations.CreateModel(
            name='DeclarationM2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m2', models.FloatField()),
                ('quartier', models.CharField(blank=True, max_length=60)),
                ('commentaire', models.CharField(blank=True, max_length=140)),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='core.defiville')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_m2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_declaration'],
            },
        ),
    ]
