# Generated by Django 5.2.3 on 2026-08-16 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_declaration_m2'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesalon',
            name='defi_ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_salon', to='core.defiville'),
        ),
        migrations.AddField(
            model_name='messagesalon',
            name='duel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_salon', to='core.duel'),
        ),
        migrations.AddField(
            model_name='messagesalon',
            name='etape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_salon', to='core.etapepatron'),
        ),
        migrations.AddField(
            model_name='messagesalon',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentions_salon', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagesalon',
            name='patron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_salon', to='core.patron'),
        ),
        migrations.AddField(
            model_name='messagesalon',
            name='vetement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_salon', to='core.vetement'),
        ),
        migrations.AddField(
            model_name='salon',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salons_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salon',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagesalon',
            name='type_message',
            field=models.CharField(choices=[('texte', 'Texte'), ('photos', 'Photos'), ('troc', 'Annonce de troc'), ('patron', 'Patron partagé'), ('etape', 'Étape de patron'), ('tissu', 'Tissu de la banque'), ('defi_ville', 'Défi de ville'), ('duel', 'Invitation à un duel')], default='texte', max_length=12),
        ),
        migrations.AlterField(
            model_name='salon',
            name='type_salon',
            field=models.CharField(choices=[('quartier', 'Quartier'), ('sos', 'SOS en direct'), ('theme', 'Thématique'), ('prive', 'Entre amies')], default='quartier', max_length=12),
        ),
    ]
