# Generated by Django 5.2.3 on 2026-08-16 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_salons_riches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesalon',
            name='coeurs',
        ),
        migrations.AddField(
            model_name='messagesalon',
            name='ecusson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_salon', to='core.ecusson'),
        ),
        migrations.AddField(
            model_name='messagesalon',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_salon', to='core.evenementcommunaute'),
        ),
        migrations.AlterField(
            model_name='messagesalon',
            name='type_message',
            field=models.CharField(choices=[('texte', 'Texte'), ('photos', 'Photos'), ('troc', 'Annonce de troc'), ('patron', 'Patron partagé'), ('etape', 'Étape de patron'), ('tissu', 'Tissu de la banque'), ('defi_ville', 'Défi de ville'), ('duel', 'Invitation à un duel'), ('evenement', "Rendez-vous de l'agenda"), ('ecusson', 'Écusson obtenu')], default='texte', max_length=12),
        ),
        migrations.CreateModel(
            name='ReactionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=8)),
                ('date_reaction', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.messagesalon')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_salon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_reaction'],
                'unique_together': {('message', 'utilisateur', 'emoji')},
            },
        ),
    ]
