# Generated by Django 5.2.3 on 2026-08-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_chat_reactions_et_widgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiljeu',
            name='jours_geles',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salon',
            name='est_mp',
            field=models.BooleanField(default=False),
        ),
    ]
