"""
Django settings for lafabrique project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


# SECURITY WARNING: don't run with debug turned on in production!
# Par défaut DEBUG est désactivé : il faut explicitement DJANGO_DEBUG=True en local.
DEBUG = _env_bool('DJANGO_DEBUG', False)

# SECURITY WARNING: keep the secret key used in production secret!
# La clé est lue depuis l'environnement. En dev (DEBUG=True) on tolère un repli ;
# en production l'absence de DJANGO_SECRET_KEY fait échouer le démarrage volontairement.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-do-not-use-in-production'
    else:
        raise ImproperlyConfigured(
            "La variable d'environnement DJANGO_SECRET_KEY est obligatoire en production. "
            "Générez-en une avec : python -c \"import secrets; print(secrets.token_urlsafe(64))\""
        )

# Hôtes autorisés : 127.0.0.1/localhost en dev + domaines passés via env.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
_extra_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', 'la-fabrique.onrender.com')
ALLOWED_HOSTS += [h.strip() for h in _extra_hosts.split(',') if h.strip()]

# Render expose automatiquement le hostname public.
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_host:
    ALLOWED_HOSTS.append(_render_host)

# Origines de confiance pour la protection CSRF (Django 4+ l'exige derrière HTTPS).
CSRF_TRUSTED_ORIGINS = [
    f'https://{h}' for h in ALLOWED_HOSTS if h not in ('127.0.0.1', 'localhost')
]

# ── Durcissement production (actif uniquement hors DEBUG) ───────────────────
if not DEBUG:
    # Render (et la plupart des PaaS) terminent le TLS au niveau du proxy.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True

    # HSTS : forcer HTTPS côté navigateur pendant 1 an.
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'

# Limite la taille des requêtes (les photos sont envoyées en base64 dans le POST).
# ~10 Mo : assez pour une photo, tout en bornant la surface de déni de service.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'anymail',
    'core',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lafabrique.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.feature_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'lafabrique.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Configuration locale par défaut (SQLite)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Si la variable DATABASE_URL existe (ce qui sera le cas sur Render), on écrase la configuration
database_url = os.environ.get("DATABASE_URL")
if database_url:
    DATABASES['default'] = dj_database_url.config(default=database_url, conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL')

STORAGES = {
    "default": {
        "BACKEND": (
            "cloudinary_storage.storage.MediaCloudinaryStorage"
            if CLOUDINARY_URL
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": "core.storage.PatchedCompressedManifestStaticFilesStorage",
    },
}
# django-cloudinary-storage vérifie settings.STATICFILES_STORAGE directement
STATICFILES_STORAGE = "core.storage.PatchedCompressedManifestStaticFilesStorage"

AUTH_USER_MODEL = 'core.Utilisateur'

AUTHENTICATION_BACKENDS = [
    'core.backends.EmailOrUsernameBackend',
]


LOGIN_REDIRECT_URL = 'dashboard'

LOGOUT_REDIRECT_URL = 'home' 

LOGIN_URL = 'connexion'

# ── Fonctionnalités (feature flags) ─────────────────────────────────────────
# Communauté « atelier » (onglet Partage). Ouverte par défaut depuis la
# refonte des écrans 37a/46a/46b. Pour la refermer (bêta, incident…) :
# définir COMMUNAUTE_ACTIVE=False dans l'environnement — les vues et les URL
# restent en place, seul l'accès est bloqué.
COMMUNAUTE_ACTIVE = _env_bool('COMMUNAUTE_ACTIVE', True)

# Détourage automatique par segmentation IA (rembg) côté serveur.
# À False : pas de détection automatique, l'utilisateur place les points à la
# main (l'ancien algorithme par seuillage colorimétrique a été supprimé).
# Désactivé par défaut : rembg (onnxruntime + modèle) fait dépasser les 512 Mo
# de l'instance Render et provoque des crashs mémoire (voir aussi le login,
# qui échoue par ricochet quand l'instance est tuée pour OOM).
REMBG_DETOURAGE_ENABLED = _env_bool('REMBG_DETOURAGE_ENABLED', False)

# ── E-mail (réinitialisation de mot de passe) ───────────────────────────────
# En dev : les e-mails s'affichent dans la console (aucune config requise).
# En prod : renseigner les variables SMTP (EMAIL_HOST, EMAIL_HOST_USER, …) via
# l'environnement ; sinon les e-mails de réinitialisation ne partiront pas.
EMAIL_BACKEND = os.environ.get(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'La Fabrique <noreply@lafabrique.app>')
# Empêche une connexion SMTP de bloquer indéfiniment la requête (et de tuer le worker).
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))

# Si une clé API Brevo est fournie, on envoie via l'API HTTP (port 443) au lieu du
# SMTP. INDISPENSABLE sur Render, qui bloque les ports SMTP sortants (25/465/587)
# → le SMTP y échoue toujours en "TimeoutError". L'API HTTP, elle, passe.
BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '')
if BREVO_API_KEY:
    EMAIL_BACKEND = 'anymail.backends.brevo.EmailBackend'
    ANYMAIL = {'BREVO_API_KEY': BREVO_API_KEY}

# ── Journalisation (visible dans la console / les logs Render) ──────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '[{levelname}] {asctime} {name} — {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        'core': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Logging : avec DEBUG=False, on veut quand même voir les erreurs dans les logs
# (console → capturée par Render / gunicorn).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}